"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BingNojsSERP = exports.GoogleMobileSERP = exports.GoogleSERP = exports.GoogleNojsSERP = void 0;
const bing_nojs_1 = require("./bing-nojs");
Object.defineProperty(exports, "BingNojsSERP", { enumerable: true, get: function () { return bing_nojs_1.BingNojsSERP; } });
const google_1 = require("./google");
Object.defineProperty(exports, "GoogleSERP", { enumerable: true, get: function () { return google_1.GoogleSERP; } });
const google_mobile_1 = require("./google-mobile");
Object.defineProperty(exports, "GoogleMobileSERP", { enumerable: true, get: function () { return google_mobile_1.GoogleMobileSERP; } });
const google_nojs_1 = require("./google-nojs");
Object.defineProperty(exports, "GoogleNojsSERP", { enumerable: true, get: function () { return google_nojs_1.GoogleNojsSERP; } });
